import { Space_Grotesk } from "next/font/google";

import "./globals.css";

const font = Space_Grotesk({
  fallback: ["sans-serif"],
  weight: ["300", "400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${font.className} m-4`}>{children}</body>
    </html>
  );
}
